### ISSUE TITLE
使用mutex跑死

### ISSUE THREAD

**Issue by chengshuihang** [azure-rtos/threadx#195] opened 2022-06-21 08:38 UTC
您好，我在使用mutex的过程中，出现了跑死的问题。
下面是跑死时候的资源截图
![image](https://user-images.githubusercontent.com/45716763/174749299-ffd3dfb4-faed-4167-9cae-4be2b4b2c400.png)
下面截图是mutex资源的截图
![image](https://user-images.githubusercontent.com/45716763/174749707-ec6270f7-4bf2-40fe-b7e7-f9dd5e790cda.png)
下面是我现在使用mutex的代码
`/*
 * fx_stm32_sdmmc1_driver.c
 *
 *  Created on: Apr 6, 2022
 *      Author: chengshuihang
 */

/* Include necessary system files.  */

#include "tx_api.h"
#include "fx_api.h"
#include "fx_user.h"

//#define SD_DETECT_PIN         CardCD_Pin
//#define SD_DETECT_GPIO_PORT   CardCD_GPIO_Port

/* Define semaphore for media transfer.  */
static TX_SEMAPHORE semaphore_transfer;
static TX_MUTEX mutex_transfer;
static         	__ALIGNED(4) uint8_t rx_dma_buff[512];
static         	__ALIGNED(4) uint8_t tx_dma_buff[512];

VOID  _fx_stm32_sdmmc1_driver(FX_MEDIA *media_ptr);
static void wait_DMA_read_complete();
static void wait_DMA_write_complete();
static void wait_transfer_ok();

UINT  _fx_partition_offset_calculate(void  *partition_sector, UINT partition,
                                     ULONG *partition_start, ULONG *partition_size);

void BSP_SDMMC1_WriteCpltCallback(void)
{
    /* Put semaphore for transfer completion.  */
    tx_semaphore_put(&semaphore_transfer);
}

/**
  * @brief BSP Rx Transfer completed callbacks
  * @param None
  * @retval None
  */
void BSP_SDMMC1_ReadCpltCallback(void)
{
    /* Put semaphore for transfer completion.  */
    tx_semaphore_put(&semaphore_transfer);
}

int BSP_SDMMC1_Init(void)
{
	UINT status;

	status = tx_semaphore_create(&semaphore_transfer, "SDMMC transfer semaphore", 0);
	if(status != TX_SUCCESS){
		return (0 - (int)status);
    }

	status = tx_mutex_create(&mutex_transfer, "SDMMC transfer mutex", TX_NO_INHERIT);
    if(status != TX_SUCCESS){
    	return (0 - (int)status);
    }

	return 0;
}

void BSP_SDMMC1_Deinit(void)
{
	tx_semaphore_delete(&semaphore_transfer);
	tx_mutex_delete(&mutex_transfer);
}

static void wait_DMA_read_complete(void)
{
    /* Wait for Rx Transfer completion */
    tx_semaphore_get(&semaphore_transfer,TX_WAIT_FOREVER);
}

static void wait_DMA_write_complete(void)
{
    /* Wait for Tx Transfer completion */
    tx_semaphore_get(&semaphore_transfer,TX_WAIT_FOREVER);
}
static void wait_transfer_ok(void)
{
    /* Wait until SDMMC card is ready to use for new operation */
    while(HAL_MMC_GetCardState(SDMMC1_HANDLE) != HAL_MMC_CARD_TRANSFER);
}

static void wait_transfer_unlock(void)
{
	tx_mutex_put(&mutex_transfer);
}

static void wait_transfer_lock(void)
{
	tx_mutex_get(&mutex_transfer, TX_WAIT_FOREVER);
}

static HAL_StatusTypeDef BSP_PlatformIsDetected(void) {
	HAL_StatusTypeDef status = HAL_OK;
    /* Check SDMMC card detect pin */
//    if(HAL_GPIO_ReadPin(SD_DETECT_GPIO_PORT, SD_DETECT_PIN) != GPIO_PIN_RESET){
//        status = HAL_ERROR;
//    }
    /* USER CODE BEGIN 1 */
    /* user code can be inserted here */
    /* USER CODE END 1 */
    return status;
}

static HAL_StatusTypeDef BSP_SDMMC_Init(void)
{
	HAL_StatusTypeDef sd_state = HAL_OK;

	/* Check if the SDMMC card is plugged in the slot */
	sd_state = BSP_PlatformIsDetected();
	if(sd_state != HAL_OK){
		return sd_state;
	}
	/* HAL SDMMC initialization */
//	HAL_SD_DeInit(SDMMC1_HANDLE);
//	sd_state = HAL_SD_Init(SDMMC1_HANDLE);

	return sd_state;
}

/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    _fx_stm32_sdmmc_driver                              PORTABLE C      */
/*                                                           6.1          */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Yuxin Zhou, Microsoft Corporation                                   */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    This function is the entry point to the STM32 SDMMC disk driver.    */
/*    It relies on the STM32 peripheral library from ST.                  */
/*                                                                        */
/*  INPUT                                                                 */
/*                                                                        */
/*    media_ptr                             Media control block pointer   */
/*                                                                        */
/*  OUTPUT                                                                */
/*                                                                        */
/*    None                                                                */
/*                                                                        */
/*  CALLS                                                                 */
/*                                                                        */
/*    _fx_utility_memory_copy               Copy sector memory            */
/*    _fx_utility_16_unsigned_read          Read 16-bit unsigned          */
/*                                                                        */
/*  CALLED BY                                                             */
/*                                                                        */
/*    FileX System Functions                                              */
/*                                                                        */
/*  RELEASE HISTORY                                                       */
/*                                                                        */
/*    DATE              NAME                      DESCRIPTION             */
/*                                                                        */
/*  05-19-2020     Yuxin Zhou               Initial Version 6.0           */
/*  09-30-2020     Yuxin Zhou               Modified comment(s),          */
/*                                            resulting in version 6.1    */
/*                                                                        */
/**************************************************************************/
VOID  _fx_stm32_sdmmc1_driver(FX_MEDIA *media_ptr)
{
	UINT        status;
	HAL_StatusTypeDef     SDMMC_Status;
	ULONG       partition_start;
	ULONG       partition_size;
	uint8_t* buffer;
	uint32_t sectors;
	uint32_t number_of_blocks;

    /* There are several useful/important pieces of information contained in the media
       structure, some of which are supplied by FileX and others are for the driver to
       setup. The following is a summary of the necessary FX_MEDIA structure members:

            FX_MEDIA Member                              Meaning

        fx_media_driver_request             FileX request type. Valid requests from FileX are
                                            as follows:

                                                    FX_DRIVER_READ
                                                    FX_DRIVER_WRITE
                                                    FX_DRIVER_FLUSH
                                                    FX_DRIVER_ABORT
                                                    FX_DRIVER_INIT
                                                    FX_DRIVER_BOOT_READ
                                                    FX_DRIVER_RELEASE_SECTORS
                                                    FX_DRIVER_BOOT_WRITE
                                                    FX_DRIVER_UNINIT

        fx_media_driver_status              This value is RETURNED by the driver. If the
                                            operation is successful, this field should be
                                            set to FX_SUCCESS for before returning. Otherwise,
                                            if an error occurred, this field should be set
                                            to FX_IO_ERROR.

        fx_media_driver_buffer              Pointer to buffer to read or write sector data.
                                            This is supplied by FileX.

        fx_media_driver_logical_sector      Logical sector FileX is requesting.

        fx_media_driver_sectors             Number of sectors FileX is requesting.

       The following is a summary of the optional FX_MEDIA structure members:

            FX_MEDIA Member                              Meaning

        fx_media_driver_info                Pointer to any additional information or memory.
                                            This is optional for the driver use and is setup
                                            from the fx_media_open call. The RAM disk uses
                                            this pointer for the RAM disk memory itself.

        fx_media_driver_write_protect       The DRIVER sets this to FX_TRUE when media is write
                                            protected. This is typically done in initialization,
                                            but can be done anytime.

        fx_media_driver_free_sector_update  The DRIVER sets this to FX_TRUE when it needs to
                                            know when clusters are released. This is important
                                            for FLASH wear-leveling drivers.

        fx_media_driver_system_write        FileX sets this flag to FX_TRUE if the sector being
                                            written is a system sector, e.g., a boot, FAT, or
                                            directory sector. The driver may choose to use this
                                            to initiate error recovery logic for greater fault
                                            tolerance.

        fx_media_driver_data_sector_read    FileX sets this flag to FX_TRUE if the sector(s) being
                                            read are file data sectors, i.e., NOT system sectors.

        fx_media_driver_sector_type         FileX sets this variable to the specific type of
                                            sector being read or written. The following sector
                                            types are identified:

                                                    FX_UNKNOWN_SECTOR
                                                    FX_BOOT_SECTOR
                                                    FX_FAT_SECTOR
                                                    FX_DIRECTORY_SECTOR
                                                    FX_DATA_SECTOR
    */

    /* Process the driver request specified in the media control block.  */
    switch(media_ptr -> fx_media_driver_request){
        case FX_DRIVER_READ:{
        	//__ALIGNED(4) uint8_t rx_dma_buff[512];

        	/* 将驱动锁上 */
        	wait_transfer_lock();
        	/* 等待EMMC状态变为可操作 */
            wait_transfer_ok();

            /*Invalidate cache before DMA read */
            //SCB_CleanInvalidateDCache_by_Addr((uint32_t*)media_ptr -> fx_media_driver_buffer,media_ptr -> fx_media_driver_sectors*512);
#if 0
            SDMMC_Status = HAL_MMC_ReadBlocks_DMA(SDMMC1_HANDLE,
            		(uint8_t*)media_ptr->fx_media_driver_buffer,
					 (media_ptr->fx_media_driver_logical_sector + media_ptr->fx_media_hidden_sectors + *((uint32_t*)media_ptr->fx_media_driver_info)),
					 media_ptr->fx_media_driver_sectors);
            SCB_InvalidateDCache_by_Addr((uint32_t*)media_ptr -> fx_media_driver_buffer,media_ptr -> fx_media_driver_sectors*512);
            /* Check status of SDMMC Read.  */
            if (SDMMC_Status == HAL_OK){
                wait_DMA_read_complete();
                /* Successful driver request.  */
                media_ptr->fx_media_driver_status = FX_SUCCESS;
            }
            else{
                /* Unsuccessful driver request.  */
                media_ptr->fx_media_driver_status = FX_IO_ERROR;
            }
#endif
            /* 获取数据缓冲区 */
            buffer = (uint8_t*)media_ptr->fx_media_driver_buffer;
            /* 获取扇区号 */
            sectors = (media_ptr->fx_media_driver_logical_sector + media_ptr->fx_media_hidden_sectors + *((uint32_t*)media_ptr->fx_media_driver_info));
            /* 获取扇区数量 */
            number_of_blocks = media_ptr->fx_media_driver_sectors;
            /* 遍历扇区读取 */
            while(number_of_blocks){
            	/* 从EMMC中读取一个扇区的数据 */
                SDMMC_Status = HAL_MMC_ReadBlocks_DMA(SDMMC1_HANDLE, rx_dma_buff, sectors, 1);
                /* 清理高速缓存 */
                SCB_InvalidateDCache_by_Addr((uint32_t*)rx_dma_buff, 512);
                /* 读取EMMC是成功的? */
                if (SDMMC_Status == HAL_OK){
                	/* 等待EMMC操作结束 */
					wait_DMA_read_complete();
					/* 设置操作成功  */
					media_ptr->fx_media_driver_status = FX_SUCCESS;
					/* 拷贝EMMC数据到缓冲中 */
	            	memcpy((void*)buffer, (const void*)rx_dma_buff, 512u);
	            	/* 扇区数量减1 */
	            	number_of_blocks--;
	            	/* 数据缓存递增512字节 */
	            	buffer += 512u;
	            	/* 扇区编号增加1 */
	            	sectors++;
				}
				else{
					/* EMMC操作失败  */
					media_ptr->fx_media_driver_status = FX_IO_ERROR;
					/* 返回退出 */
					break;
				}
            }
            /* 驱动解锁 */
            wait_transfer_unlock();
            break;
        }
        case FX_DRIVER_WRITE:{
        	//__ALIGNED(4) uint8_t tx_dma_buff[512];

        	/* 将驱动锁上 */
        	wait_transfer_lock();
        	/* 等待EMMC状态变为可操作 */
            wait_transfer_ok();
#if 0
            /*Clean cache before DMA write */
            SCB_CleanDCache_by_Addr((uint32_t*)media_ptr -> fx_media_driver_buffer,media_ptr -> fx_media_driver_sectors*512);
            /* Use the STM32 SDMMC library to write one or more sectors.  */
            SDMMC_Status = HAL_MMC_WriteBlocks_DMA(SDMMC1_HANDLE,
            		(uint8_t*)media_ptr->fx_media_driver_buffer,
					(media_ptr->fx_media_driver_logical_sector + media_ptr->fx_media_hidden_sectors + *((uint32_t*)media_ptr->fx_media_driver_info)),
					media_ptr->fx_media_driver_sectors);
            /* Check status of SDMMC Write.  */
            if (SDMMC_Status == HAL_OK){
                wait_DMA_write_complete();
                /* Successful driver request.  */
                media_ptr->fx_media_driver_status = FX_SUCCESS;
            }
            else {
                /* Unsuccessful driver request.  */
                media_ptr->fx_media_driver_status = FX_IO_ERROR;
            }
#endif
            /* 获取数据缓冲区 */
            buffer = (uint8_t*)media_ptr->fx_media_driver_buffer;
            /* 获取扇区号 */
            sectors = (media_ptr->fx_media_driver_logical_sector + media_ptr->fx_media_hidden_sectors + *((uint32_t*)media_ptr->fx_media_driver_info));
            /* 获取扇区数量 */
            number_of_blocks = media_ptr->fx_media_driver_sectors;
            /* 遍历扇区写入 */
            while(number_of_blocks){
            	/* 从缓冲区拷贝一个扇区数据到buff中 */
            	memcpy((void*)tx_dma_buff, (const void*)buffer, 512u);
            	/* 清理高速缓存 */
            	SCB_CleanDCache_by_Addr((uint32_t*)tx_dma_buff, 512);
            	/* 将buff数据写入到EMMC中 */
            	SDMMC_Status = HAL_MMC_WriteBlocks_DMA(SDMMC1_HANDLE, tx_dma_buff, sectors, 1);
                /* EMMC写入成功?  */
                if (SDMMC_Status == HAL_OK){
                	/* 等待操作结束 */
                    wait_DMA_write_complete();
                    /* 本次操作是成功的  */
                    media_ptr->fx_media_driver_status = FX_SUCCESS;
                    /* 扇区数量减1 */
                    number_of_blocks--;
                    /* buff增加512字节,一个扇区 */
	            	buffer += 512u;
	            	/* 扇区号增加 */
	            	sectors++;
                }
                else {
                    /* 操作是失败,设置为错误  */
                    media_ptr->fx_media_driver_status = FX_IO_ERROR;
                    /* 退出 */
                    break;
                }
            }
            /* 驱动解锁 */
            wait_transfer_unlock();
            break;
        }
        case FX_DRIVER_FLUSH:{
            /* Return driver success.  */
            media_ptr->fx_media_driver_status = FX_SUCCESS;
            break;
        }

		case FX_DRIVER_ABORT:{
			/* Return driver success.  */
			media_ptr->fx_media_driver_status = FX_SUCCESS;
			break;
		}
		case FX_DRIVER_INIT:{
            /* FLASH drivers are responsible for setting several fields in the
            media structure, as follows:

            media_ptr -> fx_media_driver_free_sector_update
            media_ptr -> fx_media_driver_write_protect

            The fx_media_driver_free_sector_update flag is used to instruct
            FileX to inform the driver whenever sectors are not being used.
            This is especially useful for FLASH managers so they don't have
            maintain mapping for sectors no longer in use.

            The fx_media_driver_write_protect flag can be set anytime by the
            driver to indicate the media is not writable.  Write attempts made
            when this flag is set are returned as errors.  */

            /* Perform basic initialization here... since the boot record is going
            to be read subsequently and again for volume name requests.  */

//            if(tx_semaphore_create(&semaphore_transfer, "SDMMC transfer semaphore", 0) != TX_SUCCESS){
//                /* Unsuccessful driver request.  */
//                media_ptr->fx_media_driver_status = FX_IO_ERROR;
//                break;
//            }
            /* SDMMC Initialize.  */
            SDMMC_Status = BSP_SDMMC_Init();
            /* Check status of SDMMC Initialize.  */
            if (SDMMC_Status == HAL_OK){
                /* Successful driver request.  */
                media_ptr->fx_media_driver_status = FX_SUCCESS;
            }
            else{
                /* Unsuccessful driver request.  */
                media_ptr->fx_media_driver_status = FX_IO_ERROR;
            }
            break;
        }
        case FX_DRIVER_UNINIT:{
            /* There is nothing to do in this case for the RAM driver.  For actual
               devices some shutdown processing may be necessary.  */
            //tx_semaphore_delete(&semaphore_transfer);
            /* Successful driver request.  */
            media_ptr->fx_media_driver_status = FX_SUCCESS;
            break;
        }
        case FX_DRIVER_BOOT_READ:{
        	//__ALIGNED(4) uint8_t rx_dma_buff[512];

        	wait_transfer_lock();
            wait_transfer_ok();
            /*Invalidate cache before DMA read */
            //SCB_CleanInvalidateDCache_by_Addr((uint32_t*)media_ptr -> fx_media_driver_buffer,512);
            /* Read the boot record of 512 bytes.  */
#if 0
            SDMMC_Status = HAL_MMC_ReadBlocks_DMA(SDMMC1_HANDLE,
            		(uint8_t*)media_ptr->fx_media_driver_buffer, 0u + *((uint32_t*)media_ptr->fx_media_driver_info), 1u);
            SCB_InvalidateDCache_by_Addr((uint32_t*)media_ptr -> fx_media_driver_buffer,512);
#endif
            buffer = (uint8_t*)media_ptr->fx_media_driver_buffer;
            sectors = *((uint32_t*)media_ptr->fx_media_driver_info);
            SDMMC_Status = HAL_MMC_ReadBlocks_DMA(SDMMC1_HANDLE, rx_dma_buff, sectors, 1);
            SCB_InvalidateDCache_by_Addr((uint32_t*)rx_dma_buff, 512);
            /* Check status of SDMMC Read.  */
            if (SDMMC_Status != HAL_OK){
                /* Unsuccessful driver request.  */
                media_ptr->fx_media_driver_status = FX_IO_ERROR;
                wait_transfer_unlock();
                return;
            }
            /* Wait for Rx Transfer completion */
            wait_DMA_read_complete();
            memcpy((void*)buffer, (const void*)rx_dma_buff, 512u);
            /* Determine if we have the parition... */
            partition_start =  0;
            status =  _fx_partition_offset_calculate(media_ptr->fx_media_driver_buffer, 0,
                                                     &partition_start, &partition_size);

            /* Check partition read error.  */
            if (status){
                /* Unsuccessful driver request.  */
                media_ptr->fx_media_driver_status = FX_IO_ERROR;
                wait_transfer_unlock();
                return;
            }

            /* Now determine if there is a partition...   */
            if (partition_start){
                wait_transfer_ok();
                /*Invalidate cache before DMA read */
                //SCB_CleanInvalidateDCache_by_Addr((uint32_t*)media_ptr -> fx_media_driver_buffer,512);

                /* Yes, now lets read the actual boot record.  */
#if 0
                SDMMC_Status = HAL_MMC_ReadBlocks_DMA(SDMMC1_HANDLE,
                		(uint8_t *)media_ptr->fx_media_driver_buffer, partition_start + *((uint32_t*)media_ptr->fx_media_driver_info), 1u);
                SCB_InvalidateDCache_by_Addr((uint32_t*)media_ptr -> fx_media_driver_buffer,512);
#endif
                buffer = (uint8_t*)media_ptr->fx_media_driver_buffer;
                sectors = partition_start + *((uint32_t*)media_ptr->fx_media_driver_info);
                SDMMC_Status = HAL_MMC_ReadBlocks_DMA(SDMMC1_HANDLE, rx_dma_buff, sectors, 1);
                SCB_InvalidateDCache_by_Addr((uint32_t*)rx_dma_buff, 512);
                /* Check status of SDMMC Read.  */
                if (SDMMC_Status != HAL_OK){
                    /* Unsuccessful driver request.  */
                    media_ptr->fx_media_driver_status = FX_IO_ERROR;
                    wait_transfer_unlock();
                    return;
                }
                /* Wait for Rx Transfer completion */
                wait_DMA_read_complete();
                memcpy((void*)buffer, (const void*)rx_dma_buff, 512u);
            }

            /* Successful driver request.  */
            media_ptr->fx_media_driver_status = FX_SUCCESS;
            wait_transfer_unlock();
            break;
        }

        case FX_DRIVER_BOOT_WRITE:{
        	//__ALIGNED(4) uint8_t tx_dma_buff[512];

        	wait_transfer_lock();
            wait_transfer_ok();
#if 0
            /*Clean cache before DMA write */
            SCB_CleanDCache_by_Addr((uint32_t*)media_ptr -> fx_media_driver_buffer,512);
            /* Write the boot record.  */
            SDMMC_Status = HAL_MMC_WriteBlocks_DMA(SDMMC1_HANDLE,
            		(uint8_t*)media_ptr->fx_media_driver_buffer,
					(media_ptr->fx_media_hidden_sectors + *((uint32_t*)media_ptr->fx_media_driver_info)), 1u);
#endif
            buffer = (uint8_t*)media_ptr->fx_media_driver_buffer;
            sectors = (media_ptr->fx_media_hidden_sectors + *((uint32_t*)media_ptr->fx_media_driver_info));
        	memcpy((void*)tx_dma_buff, (const void*)buffer, 512u);
        	SCB_CleanDCache_by_Addr((uint32_t*)tx_dma_buff, 512);
        	SDMMC_Status = HAL_MMC_WriteBlocks_DMA(SDMMC1_HANDLE, tx_dma_buff, sectors, 1);
            /* Check status of SDMMC Write.  */
            if (SDMMC_Status == HAL_OK){
                wait_DMA_write_complete();
                /* Successful driver request.  */
                media_ptr->fx_media_driver_status = FX_SUCCESS;
            }
            else{
                /* Unsuccessful driver request.  */
                media_ptr->fx_media_driver_status = FX_IO_ERROR;
            }
            wait_transfer_unlock();
            break ;
        }

        default:{
            /* Invalid driver request.  */
            media_ptr->fx_media_driver_status = FX_IO_ERROR;
            break;
        }
    }
}
`
在这里添加mutex的原因，是因为emmc按照大小被分成了几个FX_MEDIA的实例，在不同线程中使用，为了保证数据正确，所以添加了mutex。我mutex操作有问题吗？
下面是media_ptr -> fx_media_driver_request的值
![image](https://user-images.githubusercontent.com/45716763/174755882-3e61462a-bf07-463f-8e1c-685a85f51d24.png)

**Comment by TiejunMS** [comment] 2022-06-22 01:55
@chengshuihang , thanks for reporting issue. It looks like the issue is related to FileX. Could you move the issue to FileX repo?

**Comment by chengshuihang** [comment] 2022-06-22 02:09
我尝试了一下，将互斥锁修改为二值信号量，它将不会跑死了，目前运行的很正常，系统稳定性我还在测试。这种情况issue还需要迁移吗？

**Comment by TiejunMS** [comment] 2022-06-22 02:57
Glad to know you have solved the issue. In that case, I will just close it and there is no need to migrate to FileX issue. If you have more findings, feel free to open a new issue in FileX repository.

**Closed by TiejunMS** 2022-06-22 02:57 UTC

**Comment by chengshuihang** [comment] 2022-06-22 02:58
好的
